# Generated by Django 5.2.4 on 2025-08-20 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activate_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
