# Generated by Django 5.2.4 on 2025-08-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_used', 'Не запускалась'), ('success', 'Успешно'), ('fail', 'Не успешно')], default='not_used', verbose_name='статус')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['created_at'],
                'permissions': [('change_attempt', 'Редактирование попытки'), ('watch_attempt', 'Просмотр попытки')],
            },
        ),
        migrations.CreateModel(
            name='MailingRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('recipient_data', models.CharField(blank=True, max_length=150, null=True, verbose_name='данные получателя')),
                ('comment', models.TextField(blank=True, max_length=150, null=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'ordering': ['created_at'],
                'permissions': [('change_recipient', 'редактирование получателя'), ('watch_recipient', 'просмотр получателя')],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('create', 'Создана'), ('launched', 'Запущена'), ('completed', 'Завершена'), ('locked', 'Заблокирована')], default='create', max_length=15, verbose_name='статус')),
                ('status_comment', models.TextField(blank=True, null=True, verbose_name='комментарий к статусу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начало')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='завершение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['created_at'],
                'permissions': [('change_nws_let', 'Редактирование рассылки'), ('watch_nws_let', 'Просмотр рассылки')],
            },
        ),
        migrations.CreateModel(
            name='YourMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_topic', models.CharField(max_length=150, verbose_name='тема письма')),
                ('message', models.TextField(blank=True, max_length=5000, null=True, verbose_name='текст письма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
                'permissions': [('change_message', 'Редактирование получателя'), ('watch_message', 'Просмотр получателя')],
            },
        ),
    ]
