# Generated by Django 5.2.4 on 2025-08-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingrecipient',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='attemptsend',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.mailingrecipient', verbose_name='получатель'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='recipients',
            field=models.ManyToManyField(to='mailing.mailingrecipient', verbose_name='получатель'),
        ),
        migrations.AddField(
            model_name='attemptsend',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.newsletter', verbose_name='рассылка'),
        ),
        migrations.AddField(
            model_name='yourmessage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.yourmessage', verbose_name='сообщение'),
        ),
        migrations.AddIndex(
            model_name='mailingrecipient',
            index=models.Index(fields=['email'], name='mailing_mai_email_52a04d_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['owner'], name='mailing_new_owner_i_11476a_idx'),
        ),
    ]
