# Generated by Django 5.2.4 on 2025-08-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='название рассылки'),
        ),
    ]
