# Generated by Django 5.2.4 on 2025-08-19 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_newsletter_message_alter_newsletter_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptsend',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.newsletter', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='attemptsend',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingrecipient', verbose_name='получатель'),
        ),
    ]
